### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by martoio** [jasonwilczak/tea-cozy#1]
Your code is pretty good! One thing I would advise is to use more of the semantic elements, instead of relying on divs everywhere. 

``div`` representing an image with a caption? Why not use the [``figure``](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) element for that? 

``div`` to show a section of a site? ``section`` is made just for that.

Here's some links that explain why you use it and some of the elements available:
https://www.w3schools.com/html/html5_semantic_elements.asp
http://www.hongkiat.com/blog/html-5-semantics/
https://www.thoughtco.com/why-use-semantic-html-3468271
https://stackoverflow.com/questions/17272019/why-to-use-html5-semantic-tag-instead-of-div

**Comment by jasonwilczak** [comment]
Nice call, I updated the project to reflect those changes!
